### PR TITLE
Name the loggers after modules they annotate

### PR DESCRIPTION
**Pull request by smiszym**
This way instead of
  `DEBUG:root:...`
we get for instance
  `DEBUG:lcs.strategies.action_selection:...`
which allows for easier filtering of messages.

### CODE REVIEW

**Comment by smiszym** [comment]
Reference: https://docs.python.org/3/library/logging.html#logger-objects

**Comment by khozzy** [comment]
Ok, have you renamed all `logging` statements into `logger` in the code? It would be desired

**Comment by smiszym** [comment]
Not all yet, I can follow up.

**Comment by khozzy** [comment]
Please do so - we'll be consistent.

**Comment by smiszym** [comment]
That's all occurences I could find.

**Pull request merged**
