### PR TITLE
Probability-Enhanced Effects (PEE) implementation

### PR DESCRIPTION
**Pull request by smiszym**
This is the Python rewrite of Martin Butz's C++ implementation of the PEE mechanism for ACS, which he proposed together with D. E. Goldberg and W. Stolzmann.

This is my engineering thesis, cleaned up and updated to the current master.

I took great care not to break existing code - everything runs the same unless `do_pee` configuration flag is flipped to `True`. However, if something is broken after these changes, let me know.

I tested PEEs with maze environments. Others may or may not work, unfortunately.

If something is unclear or wrong, please raise a question in this pull request.

Thanks in advance for looking at this :)

### CODE REVIEW

**Comment by smiszym** [comment]
Fun fact: GitHub sorts the list of commits by commit date, not by their actual order (and parent-child relationship) in Git history. This is a bit confusing :)

**Comment by smiszym** [comment]
Now the pytest errors on Travis are very strange and look like a bug in pytest... Do you reproduce that on your workstation?

**Comment by khozzy** [comment]
Hi, I adjusted the PR to new changes as a separate pull-request https://github.com/ParrotPrediction/pyalcs/pull/53.

I will reject this one.

Thanks for help :)

**Comment by smiszym** [comment]
Sure!

**Pull request closed without merging**
